version: '3'
services:
    dog-breed-api:
        build: .
        command: bash -c "python3 code/dogapi/manage.py runserver 0.0.0.0:8000"
        ports: 
            - "8000:8000"
        volumes: 
            - ./code:/code
