# Generated by Django 4.2.6 on 2023-10-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeddb',
            name='exerciseneeds',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='breeddb',
            name='friendliness',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='breeddb',
            name='sheddingamount',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='breeddb',
            name='size',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='breeddb',
            name='trainability',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dogdb',
            name='age',
            field=models.CharField(max_length=30),
        ),
    ]
