# Generated by Django 4.2.6 on 2023-10-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_breeddb_exerciseneeds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogdb',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
